language: node_js
node_js:
  - "node"

#addons:
#    code_climate:
#      repo_token:

jobs:
    include:
      - stage: test
        script: ./node_modules/.bin/eslint .;
        script: npm test -- --coverage;

after_success:
  - npm install -g codeclimate-test-reporter
#  - codeclimate-test-reporter < coverage/lcov.info
