language: node_js
node_js:
  - "node"

addons:
    code_climate:
      repo_token: c684203b4c61cf1873a7e639628889a28a73699622d5847798ce7591ecd2c333

jobs:
    include:
      - script: ./node_modules/.bin/eslint .;
      - script: npm test -- --coverage;
      - stage: deploy
        script: npm run build;
        deploy:
          provider: pages
          local_dir: build/
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          on:
            branch: master


after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
